// actifTypeMappings.tsx
// This file contains TypeScript mappings for actifTypes and their corresponding brands

import { ActifType } from "@/state/api";

// List of hardware actif types
export const hardwareActifTypes: string[] = [
  "Ordinateurs portables",
  "Ordinateur de bureau",
  "Ecran",
  "Unité central",
  "Tablets",
  "Tablettes Tactiles",
  "Tablette Graphique",
  "iPad",
  "Imprimante",
  "Accessoires Tablette",
  "Périphériques & Accessoires",
  "Sacs & Sacoches",
  "Clavier",
  "Souris",
  "Tapis",
  "Power Bank",
  "Refroidisseurs PC Portable",
  "Hub USB",
  "Support Ecran",
  "Webcam",
  "Composants Informatique",
  "Processeur",
  "Carte Graphique",
  "Barrettes Mémoire",
  "Carte Mère",
  "Boîtier",
  "Bloc d'alimentation",
  "Chargeur PC Portable",
  "Batterie PC Portable",
  "Afficheur PC Portable",
  "Ventilateur",
  "Graveurs et Lecteurs",
  "Clavier PC Portable",
  "Stockage",
  "Disque Dur",
  "Clé USB",
  "Carte Mémoire",
  "Accessoires de Stockage",
  "CD & DVD",
  "Lecteur de Cartes Mémoire",
  "Serveur Rack",
  "Serveur Tour",
  "Vidéo projecteur",
  "Haut-Parleur de Conférence",
  "Microphone Modulable",
];

// Brand mapping based on actif type
export const brandsByActifType: Record<string, string[]> = {
  // Computers
  "Ordinateurs portables": [
    "Dell",
    "HP",
    "Lenovo",
    "Apple",
    "Asus",
    "Acer",
    "MSI",
    "Microsoft",
    "Samsung",
    "Toshiba",
    "Razer",
    "LG",
  ],
  "Ordinateur de bureau": [
    "Dell",
    "HP",
    "Lenovo",
    "Apple",
    "Asus",
    "Acer",
    "MSI",
    "Alienware",
    "Intel",
    "AMD",
    "Corsair",
    "NZXT",
  ],
  "Unité central": [
    "Dell",
    "HP",
    "Lenovo",
    "Apple",
    "Asus",
    "Acer",
    "Corsair",
    "NZXT",
    "Fractal Design",
    "Thermaltake",
    "CoolerMaster",
    "SilverStone",
  ],

  // Displays
  Ecran: [
    "Dell",
    "HP",
    "LG",
    "Samsung",
    "Asus",
    "Acer",
    "MSI",
    "BenQ",
    "AOC",
    "ViewSonic",
    "Philips",
    "iiyama",
  ],
  "Support Ecran": [
    "Ergotron",
    "Amazon Basics",
    "North Bayou",
    "VIVO",
    "HUANUO",
    "Duronic",
    "BONTEC",
    "Invision",
    "FITUEYES",
    "RICOO",
    "Mount-It!",
    "VonHaus",
  ],
  "Vidéo projecteur": [
    "Epson",
    "BenQ",
    "Optoma",
    "ViewSonic",
    "Sony",
    "LG",
    "Panasonic",
    "Acer",
    "XGIMI",
    "Anker",
    "JVC",
    "NEC",
  ],

  // Tablets
  Tablets: [
    "Apple",
    "Samsung",
    "Microsoft",
    "Lenovo",
    "Huawei",
    "Amazon",
    "Asus",
    "Acer",
    "LG",
    "Google",
    "Sony",
    "Nokia",
  ],
  "Tablettes Tactiles": [
    "Apple",
    "Samsung",
    "Microsoft",
    "Lenovo",
    "Huawei",
    "Amazon",
    "Asus",
    "Acer",
    "LG",
    "Google",
    "Sony",
    "Nokia",
  ],
  "Tablette Graphique": [
    "Wacom",
    "XP-Pen",
    "Huion",
    "Apple",
    "Samsung",
    "Gaomon",
    "Ugee",
    "Parblo",
    "VEIKK",
    "ViewSonic",
    "Artisul",
    "XENCELABS",
  ],
  iPad: ["Apple"],
  "Accessoires Tablette": [
    "Apple",
    "Samsung",
    "Microsoft",
    "Logitech",
    "Targus",
    "Zagg",
    "Anker",
    "Belkin",
    "OtterBox",
    "UAG",
    "Spigen",
    "ESR",
  ],

  Imprimante: [
    "Epson",
    "Brother",
    "Xerox",
    "Lexmark",
    "Kyocera",
    "Ricoh",
    "Dell",
    "Fujitsu",
    "Konica Minolta",
    "Samsung",
  ],
  // Peripherals
  "Périphériques & Accessoires": [
    "Logitech",
    "Microsoft",
    "Corsair",
    "Razer",
    "SteelSeries",
    "HyperX",
    "Anker",
    "Belkin",
    "Targus",
    "Kensington",
    "Creative",
    "Jabra",
  ],
  "Sacs & Sacoches": [
    "Targus",
    "Samsonite",
    "SwissGear",
    "HP",
    "Dell",
    "Lenovo",
    "Thule",
    "Case Logic",
    "Kensington",
    "Timbuk2",
    "AmazonBasics",
    "KROSER",
  ],
  Clavier: [
    "Logitech",
    "Corsair",
    "Razer",
    "SteelSeries",
    "HyperX",
    "Microsoft",
    "Ducky",
    "Das Keyboard",
    "Keychron",
    "Apple",
    "Roccat",
    "Glorious",
  ],
  Souris: [
    "Logitech",
    "Corsair",
    "Razer",
    "SteelSeries",
    "HyperX",
    "Microsoft",
    "Glorious",
    "Zowie",
    "Roccat",
    "Apple",
    "Cooler Master",
    "Endgame Gear",
  ],
  Tapis: [
    "Logitech",
    "Corsair",
    "Razer",
    "SteelSeries",
    "HyperX",
    "Glorious",
    "Roccat",
    "Cooler Master",
    "Endgame Gear",
    "PECHAM",
    "KTRIO",
    "Fnatic",
  ],
  "Power Bank": [
    "Anker",
    "RAVPower",
    "Aukey",
    "Belkin",
    "Mophie",
    "Samsung",
    "Apple",
    "Xiaomi",
    "INIU",
    "ROMOSS",
    "UGREEN",
    "Baseus",
  ],
  "Refroidisseurs PC Portable": [
    "Cooler Master",
    "Thermaltake",
    "Havit",
    "TopMate",
    "KLIM",
    "AICHESON",
    "TeckNet",
    "Kootek",
    "AICHESON",
    "Targus",
    "IETS",
    "FITFORT",
  ],
  "Hub USB": [
    "Anker",
    "Belkin",
    "TP-Link",
    "Aukey",
    "Satechi",
    "CalDigit",
    "VAVA",
    "Sabrent",
    "UGREEN",
    "Baseus",
    "Plugable",
    "HooToo",
  ],
  Webcam: [
    "Logitech",
    "Microsoft",
    "Razer",
    "AverMedia",
    "Creative",
    "AUSDOM",
    "NexiGo",
    "AUKEY",
    "Anker",
    "Dell",
    "Poly",
    "Cisco",
  ],
  "Haut-Parleur de Conférence": [
    "Jabra",
    "Poly",
    "Logitech",
    "EMEET",
    "Anker",
    "Konftel",
    "Beyerdynamic",
    "Sennheiser",
    "Cisco",
    "Yealink",
    "Microsoft",
    "Shure",
  ],
  "Microphone Modulable": [
    "Blue",
    "Shure",
    "Audio-Technica",
    "Rode",
    "HyperX",
    "Razer",
    "Elgato",
    "Samson",
    "AKG",
    "Sennheiser",
    "Beyerdynamic",
    "FIFINE",
  ],

  // Components
  "Composants Informatique": [
    "Intel",
    "AMD",
    "NVIDIA",
    "Samsung",
    "Corsair",
    "Kingston",
    "Crucial",
    "Western Digital",
    "Seagate",
    "ASUS",
    "MSI",
    "Gigabyte",
  ],
  Processeur: ["Intel", "AMD"],
  "Carte Graphique": [
    "NVIDIA",
    "AMD",
    "ASUS",
    "MSI",
    "Gigabyte",
    "EVGA",
    "Sapphire",
    "Zotac",
    "PNY",
    "XFX",
    "PowerColor",
    "ASRock",
  ],
  "Barrettes Mémoire": [
    "Corsair",
    "Kingston",
    "G.Skill",
    "Crucial",
    "HyperX",
    "TeamGroup",
    "Patriot",
    "ADATA",
    "GeIL",
    "OLOy",
    "PNY",
    "Mushkin",
  ],
  "Carte Mère": [
    "ASUS",
    "MSI",
    "Gigabyte",
    "ASRock",
    "EVGA",
    "Biostar",
    "Intel",
    "Supermicro",
    "NZXT",
    "Colorful",
    "SOYO",
    "ZOTAC",
  ],
  Boîtier: [
    "Corsair",
    "NZXT",
    "Fractal Design",
    "Cooler Master",
    "Thermaltake",
    "Phanteks",
    "be quiet!",
    "Lian Li",
    "BitFenix",
    "SilverStone",
    "Antec",
    "In Win",
  ],
  "Bloc d'alimentation": [
    "Corsair",
    "EVGA",
    "Seasonic",
    "be quiet!",
    "Thermaltake",
    "Cooler Master",
    "Antec",
    "FSP",
    "XPG",
    "SuperFlower",
    "SilverStone",
    "NZXT",
  ],
  "Chargeur PC Portable": [
    "Dell",
    "HP",
    "Lenovo",
    "Apple",
    "ASUS",
    "Acer",
    "Samsung",
    "Toshiba",
    "Microsoft",
    "Anker",
    "AUKEY",
    "Belkin",
  ],
  "Batterie PC Portable": [
    "Dell",
    "HP",
    "Lenovo",
    "Apple",
    "ASUS",
    "Acer",
    "Samsung",
    "Toshiba",
    "Green Cell",
    "Battpit",
    "DTK",
    "Powerforlaptop",
  ],
  "Afficheur PC Portable": [
    "LG",
    "Samsung",
    "AUO",
    "BOE",
    "Sharp",
    "Innolux",
    "CMI",
    "Japan Display Inc.",
    "Tianma",
    "CPT",
    "LG Display",
    "AU Optronics",
  ],
  Ventilateur: [
    "Noctua",
    "Corsair",
    "be quiet!",
    "Cooler Master",
    "Thermaltake",
    "Arctic",
    "Phanteks",
    "NZXT",
    "Deepcool",
    "SilverStone",
    "Scythe",
    "Lian Li",
  ],
  "Graveurs et Lecteurs": [
    "LG",
    "ASUS",
    "Samsung",
    "Pioneer",
    "HP",
    "Hitachi-LG",
    "Buffalo",
    "Dell",
    "Lite-On",
    "Sony",
    "Plextor",
    "Verbatim",
  ],
  "Clavier PC Portable": [
    "Dell",
    "HP",
    "Lenovo",
    "Apple",
    "ASUS",
    "Acer",
    "Samsung",
    "Toshiba",
    "MSI",
    "Green Cell",
    "SunSky",
    "Replacement",
  ],

  // Storage
  Stockage: [
    "Western Digital",
    "Seagate",
    "Samsung",
    "Crucial",
    "Kingston",
    "SanDisk",
    "Toshiba",
    "Intel",
    "ADATA",
    "Transcend",
    "LaCie",
    "G-Technology",
  ],
  "Disque Dur": [
    "Western Digital",
    "Seagate",
    "Samsung",
    "Toshiba",
    "HGST",
    "LaCie",
    "G-Technology",
    "Crucial",
    "Kingston",
    "Buffalo",
    "Transcend",
    "Maxtor",
  ],
  "Clé USB": [
    "SanDisk",
    "Kingston",
    "Samsung",
    "Corsair",
    "PNY",
    "Lexar",
    "Transcend",
    "ADATA",
    "Patriot",
    "Verbatim",
    "HP",
    "Sony",
  ],
  "Carte Mémoire": [
    "SanDisk",
    "Kingston",
    "Samsung",
    "Lexar",
    "PNY",
    "Transcend",
    "ADATA",
    "Sony",
    "Patriot",
    "ProGrade",
    "Delkin",
    "Verbatim",
  ],
  "Accessoires de Stockage": [
    "Sabrent",
    "ORICO",
    "StarTech",
    "ICY BOX",
    "Inateck",
    "UGREEN",
    "Vantec",
    "Anker",
    "Unitek",
    "FIDECO",
    "SSK",
    "ELUTENG",
  ],
  "CD & DVD": [
    "Verbatim",
    "Sony",
    "HP",
    "Philips",
    "Imation",
    "Maxwell",
    "Memorex",
    "Taiyo Yuden",
    "Panasonic",
    "TDK",
    "JVC",
    "Optical Quantum",
  ],
  "Lecteur de Cartes Mémoire": [
    "Kingston",
    "SanDisk",
    "Anker",
    "UGREEN",
    "Transcend",
    "Lexar",
    "ProGrade",
    "StarTech",
    "Unitek",
    "IOGEAR",
    "SSK",
    "Vanja",
  ],

  // Servers
  "Serveur Rack": [
    "Dell",
    "HP",
    "Lenovo",
    "Cisco",
    "IBM",
    "Supermicro",
    "Oracle",
    "Fujitsu",
    "Huawei",
    "Inspur",
    "ASUS",
    "Gigabyte",
  ],
  "Serveur Tour": [
    "Dell",
    "HP",
    "Lenovo",
    "Cisco",
    "IBM",
    "Supermicro",
    "Fujitsu",
    "ASUS",
    "Gigabyte",
    "Intel",
    "Huawei",
    "Terra",
  ],
};

// Default list for types not explicitly defined
export const defaultBrands: string[] = [
  "Dell",
  "HP",
  "Lenovo",
  "Apple",
  "Asus",
  "Acer",
  "Samsung",
  "Microsoft",
  "LG",
  "Sony",
  "Other",
];

/**
 * Returns brands for a specific actif type
 * @param actifType The type of actif
 * @returns Array of brands associated with that actif type
 */
export const getBrandsForActifType = (actifType: string): string[] => {
  return brandsByActifType[actifType] || defaultBrands;
};

/**
 * Checks if an actif type is a hardware type
 * @param actifType The type to check
 * @returns Boolean indicating if it's a hardware type
 */
export const isHardwareActifType = (actifType: string): boolean => {
  return hardwareActifTypes.includes(actifType);
};

/**
 * Filters a list of actif types to only include hardware types
 * @param actifTypes Array of actif types to filter
 * @returns Filtered array of actif types that are hardware types
 */
export const filterHardwareActifTypes = (
  actifTypes: ActifType[]
): ActifType[] => {
  return actifTypes.filter((type) => hardwareActifTypes.includes(type.nom));
};
