// softwareActifTypeMappings.tsx
// This file contains TypeScript mappings for software actifTypes and their corresponding brands

import { ActifType } from "@/state/api";

// List of software actif types
export const softwareActifTypes: string[] = [
  // Operating Systems
  "Windows",
  "macOS",
  "Linux",
  "Systèmes Mobiles",

  // Office & Productivity
  "Suites Bureautiques",
  "Traitement de Texte",
  "Tableurs",
  "Logiciels de Présentation",
  "Lecteurs et Éditeurs PDF",
  "Clients Email",
  "Calendriers & Planification",
  "Prise de Notes",

  // Development & Programming
  "Environnements de Développement",
  "Éditeurs de Code",
  "Systèmes de Gestion de Base de Données",
  "Contrôle de Version",
  "Compilateurs",
  "Kits de Développement Logiciel",
  "Outils API",

  // Graphic Design & Media
  "Conception Graphique",
  "Édition Photo",
  "Édition Vidéo",
  "Modélisation 3D",
  "Conception Assistée par Ordinateur",
  "Animation",
  "Production Audio",
  "Lecteurs Multimédia",

  // Internet & Communication
  "Navigateurs Web",
  "Messagerie Instantanée",
  "VoIP & Vidéoconférence",
  "Clients FTP",
  "Développement Web",
  "Systèmes de Gestion de Contenu",

  // Business & Enterprise
  "Planification des Ressources",
  "Gestion de la Relation Client",
  "Comptabilité & Finance",
  "Gestion de Projet",
  "Business Intelligence",
  "Ressources Humaines",

  // Security & Utilities
  "Antivirus & Sécurité",
  "Pare-feu",
  "VPN",
  "Gestionnaires de Mots de Passe",
  "Sauvegarde & Récupération",
  "Compression de Fichiers",
  "Utilitaires de Disque",
  "Optimisation Système",

  // Virtualization & Cloud
  "Machines Virtuelles",
  "Conteneurisation",
  "Stockage Cloud",
  "Plateformes Cloud",
  "Applications SaaS",
];

// Brand mapping based on actif type
export const brandsBySoftwareActifType: Record<string, string[]> = {
  // Operating Systems
  Windows: ["Microsoft"],
  macOS: ["Apple"],
  Linux: [
    "Canonical",
    "Red Hat",
    "SUSE",
    "Debian",
    "Arch Linux",
    "Fedora",
    "CentOS",
    "Ubuntu",
    "Linux Mint",
    "Elementary OS",
    "Gentoo",
    "Slackware",
  ],
  "Systèmes Mobiles": [
    "Google",
    "Apple",
    "Samsung",
    "Huawei",
    "Xiaomi",
    "OPPO",
    "OnePlus",
    "Realme",
    "LG",
    "Sony",
    "Motorola",
    "HTC",
  ],

  // Office & Productivity
  "Suites Bureautiques": [
    "Microsoft",
    "Google",
    "Apple",
    "LibreOffice",
    "Apache",
    "WPS",
    "Zoho",
    "FreeOffice",
    "Calligra",
    "OnlyOffice",
    "Collabora",
    "Corel",
  ],
  "Traitement de Texte": [
    "Microsoft",
    "Google",
    "Apple",
    "LibreOffice",
    "Apache",
    "WPS",
    "Zoho",
    "FreeOffice",
    "Corel",
    "AbiWord",
    "Atlantis",
    "TextMaker",
  ],
  Tableurs: [
    "Microsoft",
    "Google",
    "Apple",
    "LibreOffice",
    "Apache",
    "WPS",
    "Zoho",
    "FreeOffice",
    "Gnumeric",
    "OnlyOffice",
    "Collabora",
    "Calligra",
  ],
  "Logiciels de Présentation": [
    "Microsoft",
    "Google",
    "Apple",
    "LibreOffice",
    "Apache",
    "WPS",
    "Zoho",
    "FreeOffice",
    "Prezi",
    "Canva",
    "Slides",
    "Beautiful.ai",
  ],
  "Lecteurs et Éditeurs PDF": [
    "Adobe",
    "Foxit",
    "Nitro",
    "PDF-XChange",
    "Sumatra",
    "Kofax",
    "PDF Expert",
    "ABBYY",
    "Nuance",
    "Qoppa",
    "Xodo",
    "PDFelement",
  ],
  "Clients Email": [
    "Microsoft",
    "Google",
    "Apple",
    "Mozilla",
    "IBM",
    "The Bat!",
    "Mailbird",
    "Opera",
    "Postbox",
    "Spark",
    "eM Client",
    "Zoho",
  ],
  "Calendriers & Planification": [
    "Microsoft",
    "Google",
    "Apple",
    "Mozilla",
    "IBM",
    "Zoho",
    "Fantastical",
    "BusyCal",
    "Calendar 366",
    "Outlook",
    "Calendar 5",
    "aCalendar",
  ],
  "Prise de Notes": [
    "Microsoft",
    "Google",
    "Apple",
    "Evernote",
    "Notion",
    "Obsidian",
    "Bear",
    "Joplin",
    "Simplenote",
    "Standard Notes",
    "Zoho",
    "Nimbus Note",
  ],

  // Development & Programming
  "Environnements de Développement": [
    "Microsoft",
    "JetBrains",
    "Apple",
    "Eclipse Foundation",
    "Google",
    "Adobe",
    "NetBeans",
    "IBM",
    "Amazon",
    "Oracle",
    "SAP",
    "Embarcadero",
  ],
  "Éditeurs de Code": [
    "Microsoft",
    "GitHub",
    "Adobe",
    "Sublime HQ",
    "Apple",
    "Vim",
    "Codemirror",
    "Notepad++",
    "Panic",
    "MacroMates",
    "Brackets",
    "CodeSandbox",
  ],
  "Systèmes de Gestion de Base de Données": [
    "Oracle",
    "Microsoft",
    "IBM",
    "SAP",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "MariaDB",
    "Teradata",
    "Amazon",
    "Google",
    "SQLite",
  ],
  "Contrôle de Version": [
    "Git",
    "GitHub",
    "GitLab",
    "Atlassian",
    "Microsoft",
    "Perforce",
    "AWS",
    "Apache",
    "Mercurial",
    "PTC",
    "Micro Focus",
    "CollabNet",
  ],
  Compilateurs: [
    "Microsoft",
    "GNU",
    "LLVM",
    "Oracle",
    "Intel",
    "IBM",
    "Embarcadero",
    "C++Builder",
    "Digital Mars",
    "Qt",
    "Go",
    "Rust",
  ],
  "Kits de Développement Logiciel": [
    "Google",
    "Apple",
    "Microsoft",
    "Oracle",
    "Amazon",
    "Facebook",
    "Twitter",
    "Salesforce",
    "Adobe",
    "Samsung",
    "Intel",
    "NVIDIA",
  ],
  "Outils API": [
    "Postman",
    "Swagger",
    "Stoplight",
    "Google",
    "MuleSoft",
    "Amazon",
    "Microsoft",
    "SmartBear",
    "Kong",
    "RapidAPI",
    "Apigee",
    "ReadMe",
  ],

  // Graphic Design & Media
  "Conception Graphique": [
    "Adobe",
    "Serif",
    "Corel",
    "Sketch",
    "Figma",
    "Canva",
    "Pixelmator",
    "Autodesk",
    "Xara",
    "GIMP",
    "Inkscape",
    "ACDSee",
  ],
  "Édition Photo": [
    "Adobe",
    "Skylum",
    "Corel",
    "CyberLink",
    "DxO",
    "Capture One",
    "ON1",
    "ACDSee",
    "Pixelmator",
    "Serif",
    "Exposure",
    "Zoner",
  ],
  "Édition Vidéo": [
    "Adobe",
    "Apple",
    "Blackmagic Design",
    "Sony",
    "Magix",
    "CyberLink",
    "Corel",
    "Avid",
    "TechSmith",
    "Pinnacle",
    "Wondershare",
    "VEGAS",
  ],
  "Modélisation 3D": [
    "Autodesk",
    "Blender",
    "Maxon",
    "Dassault",
    "Trimble",
    "Foundry",
    "Luxion",
    "SideFX",
    "NewTek",
    "Pixologic",
    "Adobe",
    "Unity",
  ],
  "Conception Assistée par Ordinateur": [
    "Autodesk",
    "Dassault",
    "PTC",
    "Siemens",
    "Trimble",
    "Bentley",
    "Hexagon",
    "Vectorworks",
    "Nemetschek",
    "Bricsys",
    "ANSYS",
    "Altair",
  ],
  Animation: [
    "Adobe",
    "Maxon",
    "Autodesk",
    "Toon Boom",
    "TVPaint",
    "Reallusion",
    "SideFX",
    "Blender",
    "Unity",
    "Epic Games",
    "Smith Micro",
    "Synfig",
  ],
  "Production Audio": [
    "Avid",
    "Steinberg",
    "Image-Line",
    "Ableton",
    "Apple",
    "PreSonus",
    "Native Instruments",
    "Propellerhead",
    "Cockos",
    "Magix",
    "Bitwig",
    "Acoustica",
  ],
  "Lecteurs Multimédia": [
    "VLC",
    "Microsoft",
    "Apple",
    "Winamp",
    "MPC-HC",
    "PotPlayer",
    "KMPlayer",
    "GOM",
    "Plex",
    "Kodi",
    "MediaMonkey",
    "foobar2000",
  ],

  // Internet & Communication
  "Navigateurs Web": [
    "Google",
    "Mozilla",
    "Microsoft",
    "Apple",
    "Opera",
    "Brave",
    "Vivaldi",
    "Epic",
    "Torch",
    "Yandex",
    "Maxthon",
    "Chromium",
  ],
  "Messagerie Instantanée": [
    "Microsoft",
    "Meta",
    "Telegram",
    "Discord",
    "Signal",
    "Viber",
    "Tencent",
    "Element",
    "Zoom",
    "LINE",
    "Keybase",
    "Threema",
  ],
  "VoIP & Vidéoconférence": [
    "Zoom",
    "Microsoft",
    "Cisco",
    "LogMeIn",
    "Google",
    "BlueJeans",
    "8x8",
    "Vonage",
    "RingCentral",
    "Lifesize",
    "Jitsi",
    "Discord",
  ],
  "Clients FTP": [
    "FileZilla",
    "WinSCP",
    "Cyberduck",
    "SmartFTP",
    "CuteFTP",
    "Transmit",
    "WS_FTP",
    "ForkLift",
    "Commander One",
    "FTPShell",
    "FlashFXP",
    "CrossFTP",
  ],
  "Développement Web": [
    "Microsoft",
    "Adobe",
    "JetBrains",
    "Google",
    "GitHub",
    "Panic",
    "Bootstrap",
    "Foundation",
    "WordPress",
    "Laravel",
    "Django",
    "Ruby on Rails",
  ],
  "Systèmes de Gestion de Contenu": [
    "WordPress",
    "Joomla",
    "Drupal",
    "Wix",
    "Squarespace",
    "Shopify",
    "Adobe",
    "HubSpot",
    "Typo3",
    "Ghost",
    "Contentful",
    "Strapi",
  ],

  // Business & Enterprise
  "Planification des Ressources": [
    "SAP",
    "Oracle",
    "Microsoft",
    "Infor",
    "Sage",
    "IFS",
    "Epicor",
    "SYSPRO",
    "Acumatica",
    "Odoo",
    "NetSuite",
    "Workday",
  ],
  "Gestion de la Relation Client": [
    "Salesforce",
    "Microsoft",
    "Oracle",
    "SAP",
    "HubSpot",
    "Zoho",
    "Pipedrive",
    "SugarCRM",
    "Freshworks",
    "Insightly",
    "Apptivo",
    "Nimble",
  ],
  "Comptabilité & Finance": [
    "Intuit",
    "Sage",
    "Xero",
    "FreshBooks",
    "Wave",
    "Oracle",
    "SAP",
    "Microsoft",
    "Zoho",
    "QuickBooks",
    "Kashoo",
    "FreeAgent",
  ],
  "Gestion de Projet": [
    "Microsoft",
    "Atlassian",
    "Monday.com",
    "Asana",
    "Smartsheet",
    "Basecamp",
    "Wrike",
    "Teamwork",
    "Zoho",
    "ClickUp",
    "Notion",
    "Trello",
  ],
  "Business Intelligence": [
    "Microsoft",
    "Tableau",
    "Qlik",
    "SAP",
    "IBM",
    "Oracle",
    "SAS",
    "Domo",
    "Sisense",
    "Looker",
    "TIBCO",
    "Yellowfin",
  ],
  "Ressources Humaines": [
    "Workday",
    "SAP",
    "Oracle",
    "ADP",
    "Ultimate Software",
    "Ceridian",
    "BambooHR",
    "Zenefits",
    "Gusto",
    "Kronos",
    "Paycor",
    "Namely",
  ],

  // Security & Utilities
  "Antivirus & Sécurité": [
    "Kaspersky",
    "Norton",
    "McAfee",
    "Bitdefender",
    "ESET",
    "Avast",
    "Trend Micro",
    "F-Secure",
    "Malwarebytes",
    "Webroot",
    "Sophos",
    "Panda",
  ],
  "Pare-feu": [
    "Fortinet",
    "Cisco",
    "Palo Alto",
    "Check Point",
    "SonicWall",
    "WatchGuard",
    "Sophos",
    "Barracuda",
    "Juniper",
    "pfSense",
    "Untangle",
    "ZoneAlarm",
  ],
  VPN: [
    "NordVPN",
    "ExpressVPN",
    "CyberGhost",
    "Private Internet Access",
    "Surfshark",
    "IPVanish",
    "Proton VPN",
    "TunnelBear",
    "Mullvad",
    "Windscribe",
    "VyprVPN",
    "StrongVPN",
  ],
  "Gestionnaires de Mots de Passe": [
    "LastPass",
    "Dashlane",
    "1Password",
    "Bitwarden",
    "Keeper",
    "RoboForm",
    "NordPass",
    "Enpass",
    "KeePass",
    "Password Safe",
    "Zoho Vault",
    "True Key",
  ],
  "Sauvegarde & Récupération": [
    "Acronis",
    "Veeam",
    "Veritas",
    "Commvault",
    "Carbonite",
    "Backblaze",
    "AOMEI",
    "EaseUS",
    "Macrium",
    "R-Drive",
    "Paragon",
    "IDrive",
  ],
  "Compression de Fichiers": [
    "WinZip",
    "WinRAR",
    "7-Zip",
    "PeaZip",
    "Bandizip",
    "PowerArchiver",
    "B1",
    "Ashampoo",
    "Express Zip",
    "Zipware",
    "WinArchiver",
    "NXPowerLite",
  ],
  "Utilitaires de Disque": [
    "EaseUS",
    "AOMEI",
    "Paragon",
    "Acronis",
    "MiniTool",
    "Macrorit",
    "DiskGenius",
    "R-Tools",
    "O&O",
    "Active@",
    "Hard Disk Manager",
    "DiskInternals",
  ],
  "Optimisation Système": [
    "Piriform",
    "IObit",
    "Auslogics",
    "Wise",
    "Glary",
    "Ashampoo",
    "Norton",
    "AVG",
    "CleanMyMac",
    "MacPaw",
    "Iolo",
    "SlimCleaner",
  ],

  // Virtualization & Cloud
  "Machines Virtuelles": [
    "VMware",
    "Microsoft",
    "Oracle",
    "Parallels",
    "Red Hat",
    "Citrix",
    "QEMU",
    "VirtualBox",
    "IBM",
    "Proxmox",
    "Scale Computing",
    "Nutanix",
  ],
  Conteneurisation: [
    "Docker",
    "Red Hat",
    "Canonical",
    "Google",
    "Microsoft",
    "Rancher",
    "Containerd",
    "CoreOS",
    "Kubernetes",
    "Mesosphere",
    "Cloud Foundry",
    "Amazon",
  ],
  "Stockage Cloud": [
    "Microsoft",
    "Google",
    "Amazon",
    "Dropbox",
    "Box",
    "Apple",
    "Sync.com",
    "pCloud",
    "IBM",
    "IDrive",
    "MEGA",
    "Backblaze",
  ],
  "Plateformes Cloud": [
    "Amazon",
    "Microsoft",
    "Google",
    "IBM",
    "Oracle",
    "Alibaba",
    "Tencent",
    "DigitalOcean",
    "Vultr",
    "Linode",
    "Heroku",
    "Rackspace",
  ],
  "Applications SaaS": [
    "Microsoft",
    "Google",
    "Salesforce",
    "Adobe",
    "Slack",
    "Zoom",
    "Dropbox",
    "Box",
    "DocuSign",
    "HubSpot",
    "Atlassian",
    "Zendesk",
  ],
};

// Default list for types not explicitly defined
export const defaultSoftwareBrands: string[] = [
  "Microsoft",
  "Google",
  "Apple",
  "Adobe",
  "Oracle",
  "IBM",
  "SAP",
  "Salesforce",
  "Amazon",
  "Open Source",
  "Other",
];

/**
 * Returns brands for a specific software actif type
 * @param actifType The type of software actif
 * @returns Array of brands associated with that actif type
 */
export const getBrandsForSoftwareActifType = (actifType: string): string[] => {
  return brandsBySoftwareActifType[actifType] || defaultSoftwareBrands;
};

/**
 * Checks if an actif type is a software type
 * @param actifType The type to check
 * @returns Boolean indicating if it's a software type
 */
export const isSoftwareActifType = (actifType: string): boolean => {
  return softwareActifTypes.includes(actifType);
};

/**
 * Filters a list of actif types to only include software types
 * @param actifTypes Array of actif types to filter
 * @returns Filtered array of actif types that are software types
 */
export const filterSoftwareActifTypes = (
  actifTypes: ActifType[]
): ActifType[] => {
  return actifTypes.filter((type) => softwareActifTypes.includes(type.nom));
};

/**
 * Gets all actif types (both hardware and software)
 * @param hardwareTypes Array of hardware actif types
 * @param softwareTypes Array of software actif types
 * @returns Combined array of all actif types
 */
export const getAllActifTypes = (
  hardwareTypes: string[],
  softwareTypes: string[] = softwareActifTypes
): string[] => {
  return [...hardwareTypes, ...softwareTypes];
};

/**
 * Gets brands for any actif type (hardware or software)
 * @param actifType The type of actif
 * @param hardwareBrands Function to get hardware brands
 * @returns Array of brands for the actif type
 */
export const getBrandsForAnyActifType = (
  actifType: string,
  hardwareBrands: (type: string) => string[]
): string[] => {
  if (softwareActifTypes.includes(actifType)) {
    return getBrandsForSoftwareActifType(actifType);
  } else {
    return hardwareBrands(actifType);
  }
};
